on:
  workflow_dispatch:
  pull_request:

env:
  # Explicitly enable filesystem watch, reduces build time by 1m30s
  # https://stackoverflow.com/questions/71559269/why-does-gradle-initializing-sometimes-take-very-long
  GRADLE_OPTS: "-Dorg.gradle.vfs.watch=true"

jobs:
  build:
    runs-on: freeyourgadget-internal
    container:
      image: codeberg.org/freeyourgadget/android-fdroid-tools:37.0.0-0-nodejs

    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set common gradle properties
        run: |
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "org.gradle.parallel=false" >> gradle.properties
          echo "org.gradle.workers.max=1" >> gradle.properties

      - name: Build
        run: |
          echo "org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC" >> gradle.properties
          echo "kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC" >> gradle.properties
          ./gradlew assembleDebug --stacktrace || touch .build_failed

      - name: Test
        run: |
          sed -i '/^org.gradle.jvmargs=/d;/^kotlin.daemon.jvmargs=/d' gradle.properties
          echo "org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC" >> gradle.properties
          echo "kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC" >> gradle.properties
          ./gradlew test || touch .tests_failed

      - name: Lint
        run: |
          sed -i '/^org.gradle.jvmargs=/d;/^kotlin.daemon.jvmargs=/d' gradle.properties
          echo "org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC" >> gradle.properties
          echo "kotlin.daemon.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC" >> gradle.properties
          ./gradlew lint || touch .lint_failed

      - name: Healthcheck
        run: |
          if [ -f .build_failed ]; then
            echo "Build failed"
          fi
          if [ -f .lint_failed ]; then
            echo "Lint failed"
          fi
          if [ -f .tests_failed ]; then
            echo "Tests failed"
          fi

      - name: apk
        run: find . -name "*.apk"

      - uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: apks
          path: ./app/build/outputs/apk/*/debug/*.apk
          if-no-files-found: error
          retention-days: 7
