/*  Copyright (C) 2026 Ariel Saghiv

    This file is part of Gadgetbridge.

    Gadgetbridge is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version. */
package nodomain.freeyourgadget.gadgetbridge.service.devices.a10pro.jl_rcsp;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class JieliRcspAuthTest {

    private static byte[] hex(String s) {
        final byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(s.substring(i * 2, i * 2 + 2), 16);
        }
        return out;
    }

    @Test
    public void parityWithTypescriptReference() {
        // Generated by research/jl_auth_parity.mjs (challenge 00 01 02 ... 0f).
        final byte[] challenge = hex("00000102030405060708090a0b0c0d0e0f");
        final byte[] expected = hex("01e5807e887bde07630b4d0e715b3e8991");
        assertArrayEquals(expected, JieliRcspAuth.getEncryptedAuthData(challenge));
    }

    @Test
    public void randomAuthDataHasCorrectFraming() {
        final byte[] random = JieliRcspAuth.getRandomAuthData();
        assertEquals(17, random.length);
        assertEquals(0x00, random[0]);
    }

    @Test
    public void encryptedAuthDataStartsWith01() {
        final byte[] challenge = new byte[17];
        final byte[] encrypted = JieliRcspAuth.getEncryptedAuthData(challenge);
        assertEquals(17, encrypted.length);
        assertEquals(0x01, encrypted[0]);
    }

    @Test(expected = IllegalArgumentException.class)
    public void rejectsBadLength() {
        JieliRcspAuth.getEncryptedAuthData(new byte[5]);
    }

    @Test
    public void constantsExposedForFrameEncoding() {
        assertNotNull(JieliRcspAuth.STATIC_KEY);
        assertEquals(16, JieliRcspAuth.STATIC_KEY.length);
        assertEquals(6, JieliRcspAuth.MAGIC.length);
    }
}
